spring.application.name=youtubeCLI
spring.main.web-application-type = none
spring.shell.interactive.enabled=true
logging.level.org.springframework.shell=DEBUG

github.token=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
Gemini.API.Key=AIzaSyBEJnoRfY-7oNyg0oY8KHUcu6hg5Dm2w7s


#project-name=projects/735336057674
#project-number=projects/735336057674